export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const SET_TODO = 'SET_TODO'
export const START_TODO_TASK = 'START_TODO_TASK'

export const SET_ASSIGNED = 'SET_ASSIGNED'
export const START_ASSIGNED_TASK = 'START_ASSIGNED_TASK'

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE'
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE'

